### Get all todos
GET http://localhost:3000/api/todos


### Get one todo
GET http://localhost:3000/api/todos/1


### Create a todo
POST http://localhost:3000/api/todos
Content-Type: application/json

{
  "title": "Learn Express with Knex"
}


### Update a todo
PUT http://localhost:3000/api/todos/1
Content-Type: application/json

{
  "title": "Learn Express and Knex deeply",
  "completed": true
}


### Delete a todo
DELETE http://localhost:3000/api/todos/1
