### GET all books
GET http://localhost:3000/books

### POST a new book
POST http://localhost:3000/books
Content-Type: application/json

{
  "title": "New Book",
  "author": "New Author"
}


### PUT update a book by ID
PUT http://localhost:3000/books/1
Content-Type: application/json

{
  "title": "Updated Title",
  "author": "Updated Author"
}


### DELETE a book by ID
DELETE http://localhost:3000/books/3